// THIS FILE IS AUTO-GENERATED BY SceneMenuGenerator.cs
// DO NOT MODIFY THIS FILE MANUALLY!

#if UNITY_EDITOR
using UnityEditor;
using UnityEditor.SceneManagement;

public static class SceneMenu
{
    [MenuItem("Tools/Scene/Refresh Scene List", false, -1)]
    public static void RefreshSceneList()
    {
        SceneMenuGenerator.Generate();
    }

    [MenuItem("Tools/Scene/Others/BezierSolution/DemoScene", false, 100)]
    public static void OpenScene_Assets_Project_Orthers_BezierSolution_Demo_DemoScene_unity()
    {
        OpenScene("Assets/Project/Orthers/BezierSolution/Demo/DemoScene.unity");
    }

    [MenuItem("Tools/Scene/Others/FatMachines/DemoScene", false, 101)]
    public static void OpenScene_Assets_Project_Orthers_FatMachines_TapticFeedback_DemoScene_unity()
    {
        OpenScene("Assets/Project/Orthers/FatMachines/TapticFeedback/DemoScene.unity");
    }

    [MenuItem("Tools/Scene/Others/FreeGroundCreator/Demo", false, 102)]
    public static void OpenScene_Assets_Project_Orthers_FreeGroundCreator_Scene_Demo_unity()
    {
        OpenScene("Assets/Project/Orthers/FreeGroundCreator/Scene/Demo.unity");
    }

    [MenuItem("Tools/Scene/Others/MoveBlock/ColorBlock", false, 103)]
    public static void OpenScene_Assets_Project_Orthers_MoveBlock_ColorBlock_unity()
    {
        OpenScene("Assets/Project/Orthers/MoveBlock/ColorBlock.unity");
    }

    [MenuItem("Tools/Scene/Others/QuickOutline/QuickOutline", false, 104)]
    public static void OpenScene_Assets_Project_Orthers_QuickOutline_Samples_Scenes_QuickOutline_unity()
    {
        OpenScene("Assets/Project/Orthers/QuickOutline/Samples/Scenes/QuickOutline.unity");
    }

    [MenuItem("Tools/Scene/Game", false, 1)]
    public static void OpenScene_Assets_Project_Scenes_Game_unity()
    {
        OpenScene("Assets/Project/Scenes/Game.unity");
    }

    [MenuItem("Tools/Scene/Splash", false, 2)]
    public static void OpenScene_Assets_Project_Scenes_Splash_unity()
    {
        OpenScene("Assets/Project/Scenes/Splash.unity");
    }

    [MenuItem("Tools/Scene/Others/SampleScene", false, 105)]
    public static void OpenScene_Assets_Scenes_SampleScene_unity()
    {
        OpenScene("Assets/Scenes/SampleScene.unity");
    }

    private static void OpenScene(string path)
    {
        if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
        {
            EditorSceneManager.OpenScene(path);
        }
    }
}
#endif
