#if UNITY_EDITOR
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

[InitializeOnLoad]
public static class SceneMenuGenerator
{
    private const string FilePath = "Assets/Project/Scripts/Editor/SceneMenu.cs";

    static SceneMenuGenerator()
    {
        if (!File.Exists(FilePath))
        {
            Generate();
        }
    }

    public static void Generate()
    {
        string[] guids = AssetDatabase.FindAssets("t:Scene");
        var buildSettingsScenes = new System.Collections.Generic.HashSet<string>();
        foreach (var s in EditorBuildSettings.scenes)
        {
            if (s != null && !string.IsNullOrEmpty(s.path))
            {
                buildSettingsScenes.Add(s.path);
            }
        }

        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// THIS FILE IS AUTO-GENERATED BY SceneMenuGenerator.cs");
        sb.AppendLine("// DO NOT MODIFY THIS FILE MANUALLY!");
        sb.AppendLine("");
        sb.AppendLine("#if UNITY_EDITOR");
        sb.AppendLine("using UnityEditor;");
        sb.AppendLine("using UnityEditor.SceneManagement;");
        sb.AppendLine("");
        sb.AppendLine("public static class SceneMenu");
        sb.AppendLine("{");

        // Refresh Menu Item
        sb.AppendLine("    [MenuItem(\"Tools/Scene/Refresh Scene List\", false, -1)]");
        sb.AppendLine("    public static void RefreshSceneList()");
        sb.AppendLine("    {");
        sb.AppendLine("        SceneMenuGenerator.Generate();");
        sb.AppendLine("    }");
        sb.AppendLine("");

        // Scene items
        int mainIndex = 1;
        int otherIndex = 100;
        
        var generatedMethods = new System.Collections.Generic.HashSet<string>();

        foreach (string guid in guids)
        {
            string path = AssetDatabase.GUIDToAssetPath(guid);
            if (!path.StartsWith("Assets/") || path.EndsWith(".unitypackage") || path.Contains("TextMesh Pro/")) continue;

            string sceneName = Path.GetFileNameWithoutExtension(path);
            bool isMainScene = buildSettingsScenes.Contains(path) || path.StartsWith("Assets/Project/Scenes/");

            string menuPath;
            int priority;

            if (isMainScene)
            {
                menuPath = "Tools/Scene/" + sceneName;
                priority = mainIndex++;
            }
            else if (path.StartsWith("Assets/TextMesh Pro/"))
            {
                menuPath = "Tools/Scene/TextMesh Pro/" + sceneName;
                priority = otherIndex++;
            }
            else if (path.StartsWith("Assets/Project/Orthers/"))
            {
                string relative = path.Substring("Assets/Project/Orthers/".Length);
                string[] parts = relative.Split('/');
                if (parts.Length > 1)
                {
                    menuPath = "Tools/Scene/Others/" + parts[0] + "/" + sceneName;
                }
                else
                {
                    menuPath = "Tools/Scene/Others/" + sceneName;
                }
                priority = otherIndex++;
            }
            else
            {
                menuPath = "Tools/Scene/Others/" + sceneName;
                priority = otherIndex++;
            }

            // Create a valid C# method name
            string safeMethodName = "OpenScene_" + path.Replace("/", "_").Replace("\\", "_").Replace(".", "_").Replace(" ", "_").Replace("-", "_").Replace("&", "_").Replace("(", "_").Replace(")", "_");
            
            // Just in case there are duplicate names, make it unique
            if (generatedMethods.Contains(safeMethodName))
            {
                int suffix = 1;
                while (generatedMethods.Contains(safeMethodName + "_" + suffix))
                {
                    suffix++;
                }
                safeMethodName = safeMethodName + "_" + suffix;
            }
            generatedMethods.Add(safeMethodName);

            sb.AppendLine($"    [MenuItem(\"{menuPath}\", false, {priority})]");
            sb.AppendLine($"    public static void {safeMethodName}()");
            sb.AppendLine("    {");
            sb.AppendLine($"        OpenScene(\"{path}\");");
            sb.AppendLine("    }");
            sb.AppendLine("");
        }

        // OpenScene Helper
        sb.AppendLine("    private static void OpenScene(string path)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())");
        sb.AppendLine("        {");
        sb.AppendLine("            EditorSceneManager.OpenScene(path);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine("#endif");

        // Write the file
        string dir = Path.GetDirectoryName(FilePath);
        if (!Directory.Exists(dir))
        {
            Directory.CreateDirectory(dir);
        }
        File.WriteAllText(FilePath, sb.ToString(), Encoding.UTF8);
        AssetDatabase.ImportAsset(FilePath);
        Debug.Log("Scene Menu updated successfully!");
    }
}

public class SceneMenuPostprocessor : AssetPostprocessor
{
    private static void OnPostprocessAllAssets(string[] importedAssets, string[] deletedAssets, string[] movedAssets, string[] movedFromAssetPaths)
    {
        bool anySceneChanged = false;
        foreach (string str in importedAssets)
        {
            if (str.EndsWith(".unity")) { anySceneChanged = true; break; }
        }
        if (!anySceneChanged)
        {
            foreach (string str in deletedAssets)
            {
                if (str.EndsWith(".unity")) { anySceneChanged = true; break; }
            }
        }
        if (!anySceneChanged)
        {
            foreach (string str in movedAssets)
            {
                if (str.EndsWith(".unity")) { anySceneChanged = true; break; }
            }
        }

        if (anySceneChanged)
        {
            SceneMenuGenerator.Generate();
        }
    }
}
#endif
